<?php

namespace Database\Seeders;

use App\Models\AboutContent;
use App\Models\ContactInfo;
use App\Models\ExpertiseItem;
use App\Models\HeroSlide;
use App\Models\PortfolioProject;
use App\Models\Service;
use App\Models\TeamMember;
use App\Models\Testimonial;
use Illuminate\Database\Seeder;

class ContentSeeder extends Seeder
{
    public function run(): void
    {
        HeroSlide::query()->delete();
        AboutContent::query()->delete();
        Service::query()->delete();
        PortfolioProject::query()->delete();
        ExpertiseItem::query()->delete();
        TeamMember::query()->delete();
        Testimonial::query()->delete();
        ContactInfo::query()->delete();

        HeroSlide::insert([
            [
                'title' => 'Avec NIWY Tech',
                'description' => "Explorez la creativite, l'innovation et la technologie de haute qualite.",
                'cta' => 'Decouvrir nos services',
                'images' => json_encode(['code.jpeg', 'developpeur.jpeg']),
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Developpement Web',
                'description' => 'Nous creons des sites web modernes et performants.',
                'cta' => 'En savoir plus',
                'images' => json_encode(['bureau.jpg']),
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Applications Mobiles',
                'description' => 'Transformez vos idees en applications mobiles performantes.',
                'cta' => 'Decouvrir',
                'images' => json_encode(['developpeur.jpeg']),
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Innovation et IA',
                'description' => "Integrez l'intelligence artificielle dans vos processus.",
                'cta' => "Explorer l'IA",
                'images' => json_encode(['simulation.png', 'bureau.jpg']),
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cybersecurite',
                'description' => 'Protegez vos systemes et donnees.',
                'cta' => 'En savoir plus',
                'images' => json_encode(['code.jpeg', 'banner.jpg']),
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        AboutContent::create([
            'title' => 'A propos de',
            'highlight' => 'NIWY Tech',
            'intro' => 'Chez NIWY, nous croyons en la puissance de la technologie pour transformer les idees en realite. Notre mission est de fournir des solutions technologiques innovantes, modernes et intuitives, concues pour repondre aux besoins d\'un monde en constante evolution.',
            'mission_title' => 'Notre Mission',
            'mission_text' => "Offrir des solutions numeriques performantes, adaptees aux besoins des entreprises et particuliers, en mettant l'innovation au coeur de nos realisations.",
            'vision_title' => 'Notre Vision',
            'vision_text' => 'Devenir un leader technologique en revolutionnant le paysage digital grace a des services de haute qualite et une expertise inegalee.',
            'approach_title' => 'Notre Approche',
            'approach_text' => 'Nous combinons expertise technique et creativite pour creer des designs dynamiques, esthetiques et fonctionnels.',
            'services_title' => 'Nos Services',
            'services_list' => [
                'Developpement Web et Mobile',
                'Analyse de donnees',
                'Solutions technologiques innovantes',
                'Consultation digitale',
            ],
            'cta_label' => 'Contactez-nous',
            'cta_link' => '/contact',
        ]);

        Service::insert([
            [
                'slug' => 'ia',
                'title' => 'Intelligence Artificielle',
                'icon' => 'Brain',
                'description' => "Notre expertise en IA transforme votre entreprise grace a des solutions innovantes et sur mesure.",
                'features' => json_encode([
                    'Systemes de recommandation personnalises',
                    'Chatbots intelligents et assistants virtuels',
                    "Vision par ordinateur et reconnaissance d'images",
                    'Traitement du langage naturel (NLP)',
                    "Optimisation des processus metier par l'IA",
                    'Analyse predictive avancee',
                ]),
                'benefits' => json_encode([
                    'Automatisation des taches repetitives',
                    'Amelioration de la prise de decision',
                    'Personnalisation accrue des services',
                    'Reduction des couts operationnels',
                    'Augmentation de la productivite',
                ]),
                'methodology' => json_encode([
                    'Analyse approfondie des besoins',
                    'Developpement de modeles sur mesure',
                    'Tests et validation continue',
                    'Deploiement progressif',
                    'Maintenance et optimisation',
                ]),
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'ml',
                'title' => 'Machine Learning',
                'icon' => 'Cpu',
                'description' => 'Nos solutions de Machine Learning extraient des insights precieux et automatisent vos processus.',
                'features' => json_encode([
                    'Modeles de prediction avances',
                    'Analyse de donnees en temps reel',
                    'Recommandations personnalisees',
                    "Detection d'anomalies",
                    'Optimisation des modeles',
                    "Integration avec les systemes existants",
                ]),
                'benefits' => json_encode([
                    'Decisions basees sur les donnees',
                    'Reduction des erreurs humaines',
                    "Amelioration de l'efficacite operationnelle",
                    'Scalabilite des solutions',
                    'Adaptabilite aux changements',
                ]),
                'methodology' => json_encode([
                    'Collecte et preparation des donnees',
                    'Selection des algorithmes',
                    'Entrainement des modeles',
                    'Validation et tests',
                    'Deploiement et monitoring',
                ]),
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'mobile',
                'title' => 'Developpement Mobile',
                'icon' => 'Smartphone',
                'description' => 'Nous concevons des applications mobiles natives iOS et Android, adaptees a vos besoins.',
                'features' => json_encode([
                    'Applications natives pour iOS et Android',
                    'Design intuitif et responsive',
                    "Integration avec les API existantes",
                    'Notifications push personnalisees',
                    'Securite renforcee',
                    'Maintenance et mises a jour regulieres',
                ]),
                'benefits' => json_encode([
                    'Experience utilisateur optimale',
                    'Acces aux fonctionnalites natives',
                    'Performance elevee',
                    'Securite des donnees',
                    'Support technique continu',
                ]),
                'methodology' => json_encode([
                    'Analyse des besoins utilisateurs',
                    'Prototypage et conception',
                    'Developpement iteratif',
                    'Tests et validation',
                    'Deploiement et suivi',
                ]),
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'web',
                'title' => 'Developpement Web',
                'icon' => 'Code',
                'description' => 'Nous creons des sites web modernes, responsives et optimises pour le referencement.',
                'features' => json_encode([
                    'Design responsive et moderne',
                    'Optimisation SEO',
                    "Integration avec les CMS",
                    'E-commerce et paiements securises',
                    'Securite renforcee',
                    'Maintenance et mises a jour',
                ]),
                'benefits' => json_encode([
                    'Visibilite accrue en ligne',
                    "Experience utilisateur amelioree",
                    'Performance optimisee',
                    'Securite des donnees',
                    'Support technique continu',
                ]),
                'methodology' => json_encode([
                    'Analyse des besoins',
                    'Conception et prototypage',
                    'Developpement iteratif',
                    'Tests et validation',
                    'Deploiement et suivi',
                ]),
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'data',
                'title' => 'Analyse de Donnees',
                'icon' => 'BarChart3',
                'description' => 'Nous analysons vos donnees pour vous aider a prendre des decisions eclairees et strategiques.',
                'features' => json_encode([
                    'Analyse descriptive et predictive',
                    'Visualisation des donnees',
                    'Reporting personnalise',
                    "Detection d'anomalies",
                    "Integration avec les outils existants",
                    'Analyse en temps reel',
                ]),
                'benefits' => json_encode([
                    'Decisions basees sur les donnees',
                    'Identification des tendances',
                    'Optimisation des processus',
                    'Reduction des couts',
                    'Amelioration de la performance',
                ]),
                'methodology' => json_encode([
                    'Collecte des donnees',
                    'Nettoyage et preparation',
                    'Analyse et modelisation',
                    'Visualisation des resultats',
                    'Reporting et recommandations',
                ]),
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'integration',
                'title' => 'Integration',
                'icon' => 'Puzzle',
                'description' => "Nous integrons vos systemes existants pour une meilleure synergie et efficacite.",
                'features' => json_encode([
                    "Integration d'API",
                    'Migration des donnees',
                    'Synchronisation des systemes',
                    'Automatisation des workflows',
                    'Securite des donnees',
                    'Maintenance et support',
                ]),
                'benefits' => json_encode([
                    'Efficacite accrue',
                    'Reduction des couts',
                    'Amelioration de la collaboration',
                    'Securite renforcee',
                    'Scalabilite des solutions',
                ]),
                'methodology' => json_encode([
                    'Analyse des systemes existants',
                    "Planification de l'integration",
                    'Developpement et tests',
                    'Deploiement progressif',
                    'Support et maintenance',
                ]),
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        PortfolioProject::insert([
            [
                'title' => 'Site Web E-commerce',
                'description' => "Un site web e-commerce moderne et optimise pour une experience utilisateur exceptionnelle.",
                'back_text' => "Decouvrez notre projet de site web e-commerce et explorez ses fonctionnalites innovantes.",
                'image' => 'produit.jpg',
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Plateforme SaaS',
                'description' => 'Une plateforme SaaS complete pour gerer vos projets et collaborateurs en toute simplicite.',
                'back_text' => 'Explorez notre plateforme SaaS et ses outils de gestion integres.',
                'image' => 'produit2.jpeg',
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Application Mobile',
                'description' => 'Une application mobile innovante pour suivre vos objectifs de sante et de bien-etre.',
                'back_text' => 'Decouvrez notre application mobile et ses fonctionnalites uniques.',
                'image' => 'produit3.jpeg',
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => "Solution d'IA",
                'description' => "Une solution d'intelligence artificielle pour optimiser vos processus metiers.",
                'back_text' => "Explorez notre solution d'IA et ses capacites d'automatisation.",
                'image' => 'produit4.jpeg',
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Analyse de Donnees',
                'description' => "Une plateforme d'analyse de donnees pour des decisions eclairees.",
                'back_text' => "Decouvrez notre plateforme d'analyse de donnees et ses outils puissants.",
                'image' => 'produit5.jpeg',
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Solution de Cybersecurite',
                'description' => 'Une solution de cybersecurite pour proteger vos systemes et donnees.',
                'back_text' => 'Explorez notre solution de cybersecurite et ses fonctionnalites avancees.',
                'image' => 'bureau.jpg',
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        ExpertiseItem::insert([
            [
                'slug' => 'ia',
                'title' => 'Intelligence Artificielle',
                'icon' => 'Brain',
                'description' => "Nous developpons des solutions d'IA sur mesure pour automatiser vos processus et ameliorer votre efficacite.",
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'dev',
                'title' => 'Developpement de logiciels',
                'icon' => 'Code',
                'description' => 'Nous concevons des logiciels innovants et personnalises pour repondre a vos besoins specifiques.',
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'data',
                'title' => 'Analyse de donnees',
                'icon' => 'BarChart3',
                'description' => 'Nous analysons vos donnees pour vous aider a prendre des decisions eclairees et strategiques.',
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'security',
                'title' => 'Cybersecurite',
                'icon' => 'Shield',
                'description' => 'Nous protegeons vos systemes et donnees avec des solutions de cybersecurite avancees.',
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        TeamMember::insert([
            [
                'name' => 'Joseph Kabila',
                'role' => 'Collaborateur scientifique',
                'image' => 'simulation.png',
                'theme' => 'light',
                'reverse' => false,
                'summary' => json_encode([
                    "Docteur en droit du travail de l'Universite de Wurzburg (2017), diplome d'etudes superieures en droit economique et social (2012) et titulaire d'un Master en droit europeen (2013).",
                    "Il accompagne les entreprises dans leur installation ou la representation de leurs produits en RDC, avec une approche interculturelle et entrepreneuriale.",
                ]),
                'skills' => 'Droit des affaires, droit du travail et de la securite sociale, droit des assurances, gouvernance des ressources naturelles, droit international prive, droit des investissements, litiges civils et commerciaux.',
                'contact' => 'Tel. : +243 821 056 899, +49 176 277 14630 | Courriel : yves.manzanza@aequilex-partners.com',
                'is_carousel' => false,
                'socials' => null,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tshisekedi Machafu',
                'role' => 'Associee co-fondatrice',
                'image' => 'code.jpeg',
                'theme' => 'dark',
                'reverse' => true,
                'summary' => json_encode([
                    "Diplomee en droit prive et judiciaire (2007), elle a evolue dans l'humanitaire et la cooperation avant de se specialiser en assistance voyage et logistique.",
                    "Point focal en Allemagne pour nos partenaires europeens, elle supervise aussi l'organisation des formations de renforcement des capacites.",
                ]),
                'skills' => "Droit de la famille, droit de l'immigration, droit international prive, logistique, organisation des formations.",
                'contact' => 'Tel. : +49 163 965 0271, +49 176 710 71771 | Courriel : mimie.manzanza@aequilex-partners.com',
                'is_carousel' => false,
                'socials' => null,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Goma Mutu',
                'role' => 'Defenseur judiciaire',
                'image' => 'logo.jpeg',
                'theme' => 'light',
                'reverse' => false,
                'summary' => json_encode([
                    "Licencie en droit public (2022), il combine une solide formation academique a une experience de conseil et de defense judiciaire.",
                    "Il accompagne les entreprises dans leurs procedures d'installation et propose des solutions adaptees aux besoins de ses clients.",
                ]),
                'skills' => 'Relations economiques internationales, droit commercial general, droit des societes, entreprises en difficulte, organisation de formations.',
                'contact' => 'Tel. : +243 970 083 347 | Courriel : ignace.tchenga@aequilex-partners.com',
                'is_carousel' => false,
                'socials' => null,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Biden Grille',
                'role' => 'Collaborateur scientifique',
                'image' => 'ordinateur.jpg',
                'theme' => 'dark',
                'reverse' => true,
                'summary' => json_encode([
                    "Licencie en droit economique et social (2017), Master en sciences humaines et sociales (2024), avec plusieurs certifications specialisees.",
                    "Ancien agent au departement sinistres chez Allianz et charge de cours a l'Universite de Kikwit.",
                ]),
                'skills' => 'Droits des affaires, navigation, transports et logistique, droits des etrangers.',
                'contact' => 'Tel. : +243 810 508 982, +33 6 12 87 52 38 | Courriel : joel.kasanga@aequilex-partners.com',
                'is_carousel' => false,
                'socials' => null,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jean-Paul Kiala Mutiara',
                'role' => 'Avocat',
                'image' => 'simulation.png',
                'theme' => 'dark',
                'reverse' => false,
                'summary' => json_encode([
                    "Diplome agrege en droit, assistant a la Faculte de droit et avocat au Barreau de Kinshasa/Matete.",
                    "Engage sur les questions sociales d'entreprise et la representation judiciaire, il conseille les entreprises sur leur conformite.",
                ]),
                'skills' => "Droit des affaires, droit penal, droit fiscal, droit international prive, droit des marches publics, droit judiciaire.",
                'contact' => 'Tel. : +243 827 990 604 | Courriel : jean-paul.kiala@aequilex-partners.com',
                'is_carousel' => false,
                'socials' => null,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'John Heshima',
                'role' => 'Developpeur Full-Stack',
                'image' => 'JOHN.jpeg',
                'theme' => null,
                'reverse' => false,
                'summary' => null,
                'skills' => null,
                'contact' => null,
                'is_carousel' => true,
                'socials' => json_encode([
                    'linkedin' => '#',
                    'github' => '#',
                    'twitter' => '#',
                ]),
                'sort_order' => 101,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jane Smith',
                'role' => 'Developpeuse Front-End',
                'image' => 'femme.png',
                'theme' => null,
                'reverse' => false,
                'summary' => null,
                'skills' => null,
                'contact' => null,
                'is_carousel' => true,
                'socials' => json_encode([
                    'linkedin' => '#',
                    'github' => '#',
                    'twitter' => '#',
                ]),
                'sort_order' => 102,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'John Johnson',
                'role' => 'Developpeur Back-End',
                'image' => 'homme2.jpeg',
                'theme' => null,
                'reverse' => false,
                'summary' => null,
                'skills' => null,
                'contact' => null,
                'is_carousel' => true,
                'socials' => json_encode([
                    'linkedin' => '#',
                    'github' => '#',
                    'twitter' => '#',
                ]),
                'sort_order' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bob Brown',
                'role' => 'Developpeur Mobile',
                'image' => 'homme.jpeg',
                'theme' => null,
                'reverse' => false,
                'summary' => null,
                'skills' => null,
                'contact' => null,
                'is_carousel' => true,
                'socials' => json_encode([
                    'linkedin' => '#',
                    'github' => '#',
                    'twitter' => '#',
                ]),
                'sort_order' => 104,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ellen Ross',
                'role' => 'Product Designer',
                'image' => 'developpeur.jpeg',
                'theme' => null,
                'reverse' => false,
                'summary' => null,
                'skills' => null,
                'contact' => null,
                'is_carousel' => true,
                'socials' => json_encode([
                    'linkedin' => '#',
                    'github' => '#',
                    'twitter' => '#',
                ]),
                'sort_order' => 105,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Victor N.',
                'role' => 'Data Engineer',
                'image' => 'JOHN.jpeg',
                'theme' => null,
                'reverse' => false,
                'summary' => null,
                'skills' => null,
                'contact' => null,
                'is_carousel' => true,
                'socials' => json_encode([
                    'linkedin' => '#',
                    'github' => '#',
                    'twitter' => '#',
                ]),
                'sort_order' => 106,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Grace K.',
                'role' => 'Project Manager',
                'image' => 'femme.png',
                'theme' => null,
                'reverse' => false,
                'summary' => null,
                'skills' => null,
                'contact' => null,
                'is_carousel' => true,
                'socials' => json_encode([
                    'linkedin' => '#',
                    'github' => '#',
                    'twitter' => '#',
                ]),
                'sort_order' => 107,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Testimonial::insert([
            [
                'name' => 'Patrick M.',
                'role' => 'Directeur Marketing',
                'quote' => "L'equipe NIWY a livre une plateforme solide, avec un vrai sens du detail.",
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lucie K.',
                'role' => 'Product Owner',
                'quote' => 'Un accompagnement fluide et des resultats mesurables en quelques semaines.',
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jean B.',
                'role' => 'CEO',
                'quote' => 'Nos processus ont ete optimises rapidement, avec des solutions adaptees.',
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        ContactInfo::create([
            'phone' => '+243 00 000 00 00',
            'email' => 'contact@niwytech.com',
            'address' => '123 Avenue Colonel Ebeya, Kinshasa',
            'hours' => 'Lun-Ven: 8h-18h',
            'map_embed_url' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3979.8587677916214!2d15.3120183!3d-4.3115287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1a6a33a428e3b6c3%3A0x2f23b6d8f6d63f0!2sAvenue%20Colonel%20Ebeya%2C%20Kinshasa%2C%20Democratic%20Republic%20of%20the%20Congo!5e0!3m2!1sen!2s!4v1652893456789!5m2!1sen!2s',
            'social_links' => [
                'facebook' => '#',
                'twitter' => '#',
                'linkedin' => '#',
            ],
        ]);
    }
}
